### ISSUE TITLE
RepOpt-VGG-A0-target精度达不到repvggA0？

### ISSUE THREAD

**Issue by JaciusCV** [DingXiaoH/RepOptimizers#4]
请问一下博主，使用RepOpt-VGG-A0-hs在cifar100上进行超参搜索训练的精度只有56左右，使用搜索后的超参在imagenet上，使用RepOpt-VGG-A0-target得到精度只有70多，低了repvggA0 2个点，这是为什么？

**Comment by 1079863482** [comment]
> 

你好，你这个实验有没有下文呢？

**Comment by JaciusCV** [comment]
小模型应用在其他任务中，性能不如RepVGG

**Comment by JaciusCV** [comment]
> > 
> 
> 你好，你这个实验有没有下文呢？

小模型应用在其他任务中，性能不如RepVGG
