### ISSUE TITLE
RepOptimizer如何应用在下游任务中？

### ISSUE THREAD

**Issue by JaciusCV** [DingXiaoH/RepOptimizers#5]
作者好，请问RepOptimizer应用在其他任务中，优化器只需要针对backbone网络设计,还是需要针对整个网络设计？

**Comment by ZHIZIHUABU** [comment]
你在自己的任务中应用了repopt吗，我移植到自己的模型撒上后发现ptq量化精度损失仍旧很大不如原生结构直接进行ptq量化。

**Comment by JaciusCV** [comment]
应用了，没有精度量化问题
